# Generated by Django 3.0.2 on 2020-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(default='', max_length=255)),
                ('deskripsi_barang', models.TextField(default='')),
                ('qty_barang', models.IntegerField(default=1)),
                ('tempat_beli_barang', models.CharField(default='', max_length=255)),
                ('pembeli_barang', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
