# Generated by Django 3.0.2 on 2020-01-30 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uangbulanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='harga_barang',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barang',
            name='tanggal_beli_barang',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 4, 4, 40, 629220, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
